version: "3.9"

services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      extra_hosts:
        - "juzoanya.42.fr:127.0.0.1"
    image: nginx
    container_name: NGINX
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/inception
    env_file:
      - .env
    networks:
      - default
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: WordPress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/inception
    env_file:
      - .env
    networks:
      - default
    
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: MariaDB
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - default

################
#BONUS SERVICES#
################
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    container_name: RedisServer
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/inception
    env_file:
      - .env
    networks:
      - default
  
  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    container_name: ftpServer
    restart: always
    ports:
      - "21:21"
    volumes:
      - wordpress_data:/var/www/html/inception
    env_file:
      - .env
    networks:
      - default
  
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    container_name: Adminer
    restart: always
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/inception
    env_file:
      - .env
    networks:
      - default

  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    image: cadvisor
    container_name: CAdvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - default


volumes:
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none

networks:
  default:
    name: main_network